revision = '380e35cd2264'
down_revision = 'b0e0240e4596'

"""
Revision ID: 380e35cd2264
Revises: b0e0240e4596
Create Date: 2025-07-07 10:53:11.191436

"""
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('name', sa.String(), nullable=False))
    op.add_column('brands', sa.Column('logo_url', sa.String(), nullable=False))
    op.alter_column('brands', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.drop_column('brands', 'logo')
    op.drop_column('brands', 'title')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'color')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand_id', sa.INTEGER(), nullable=True))
    op.add_column('products', sa.Column('color', sa.VARCHAR(length=50), nullable=True))
    op.add_column('products', sa.Column('rating', sa.FLOAT(), nullable=True))
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.add_column('brands', sa.Column('title', sa.VARCHAR(length=255), nullable=True))
    op.add_column('brands', sa.Column('logo', sa.VARCHAR(length=500), nullable=True))
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.alter_column('brands', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('brands', 'logo_url')
    op.drop_column('brands', 'name')
    # ### end Alembic commands ###
