"""
Revision ID: b0e0240e4596
Revises: 264609ca9a06
Create Date: 2025-07-02 09:22:45.215111

"""
from alembic import op
import sqlalchemy as sa

revision = 'b0e0240e4596'
down_revision = '264609ca9a06'
branch_labels = None
depends_on = None


def upgrade():
    # Thêm trường color vào bảng products
    op.add_column('products', sa.Column('color', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'color')
    # ### end Alembic commands ###
