"""
Revision ID: 4fb1de4c2829
Revises: b7a4f00b12f1
Create Date: 2025-07-07 11:36:38.256332

"""
from alembic import op
import sqlalchemy as sa

revision = '4fb1de4c2829'
down_revision = 'b7a4f00b12f1'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
