"""
Revision ID: b7a4f00b12f1
Revises: 0eee2ea6440b
Create Date: 2025-07-07 11:00:53.506639

"""
from alembic import op
import sqlalchemy as sa

revision = 'b7a4f00b12f1'
down_revision = '0eee2ea6440b'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
